double STC (double x,double xd, double v,double capa,double capb){
  static double zeta1,zeta2,zeta3,vl,wl,sigma,b1,c1=1,dia= 11.8,M = 2.7, ms=0.375 ,des_v=0,h1,h2;
  static double c2 = 2.5375,k1 = 0.7946,k2 = 0.2595,force,vel_integral =0;
  h1 = (capa+0.388)/0.5011;
  h2 = (capb+0.3505)/0.4743;
  zeta1 = x-xd;
  zeta2 = v;
  zeta3 = atan((h2-h1)/dia);
  b1 = 1/(M-ms*cos(zeta3)*cos(zeta3));
  sigma = c1*zeta2+c2*zeta1;
  wl = (sigma-c2*zeta1)*c2/c1;
  if(!incr) vel_integral = 0;
  vel_integral += k2*signum(sigma);
  vl = -(k1*signum(sigma)*sqrt(abs(sigma)))- vel_integral;
  force = (vl-wl)/(c1*b1);
  if(!incr) des_v = 0;
   des_v = des_v+ (force*(millis()-t_stc))/(10000*M);
   des_v = constrain(des_v, -6,6);
//  Serial.print(millis()-t_stc);
//  Serial.print('\t');
  t_stc = millis();
//  Serial.print(M);
//  Serial.print('\t');
//  Serial.print(cos(zeta3)*cos(zeta3));
//  Serial.print('\t');
  Serial.println(zeta3*10);
//  Serial.print('\t');
//  Serial.print(b1);
//  Serial.print('\t');
//  Serial.print(sigma);
//  Serial.print('\t');
//  Serial.print(h1);
//  Serial.print('\t');
//  Serial.print(h2);
//  Serial.print('\t');
//  Serial.println(force);
//  Serial.print('\t');
//  Serial.println(des_v);
  
  return des_v;
}
